version: "3.4"
services:
    postgres:
        image: postgres:alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=wirvsvirus
        volumes:
            - "db-data:/var/lib/postgresql/data"
        networks:
            - backend
    app:
        build:
            context: .
            target: dev
        restart: always
        ports:
            - "3000:3000"
            - "9229:9229" # debug port
        depends_on:
            - postgres
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/node/app
            - /node/app/node_modules
        networks:
            - backend

volumes:
    db-data:

networks:
    backend:
